spring:
  batch:
    job:
      enabled: false
  mail:
    host: smtp.qq.com
    username: 392822872@qq.com
    password: yrhmglulgsxsbgjf
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
pixiv:
  client_id:
  client_secret:
  username:
  password:
  device_token:
  refresh_token: 
sina:
  username:
  password:
imgur:
  client_id:
imageSave:
  path: E:\244\
graphicsMagick:
  path: D:\GraphicsMagick-1.3.31-Q16\gm.exe
webClient:
  domain: localhost:8080
  checkWord: 1111
thread:
  num: 1