spring:
  batch:
    job:
      enabled: false
  mail:
    host: smtp.qq.com
    username: 
    password:
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
pixiv:
  client_id:
  client_secret:
  username:
  password:
  device_token:
  refresh_token:
sina:
  username:
  password:
imgur:
  client_id:
postimage:
  apikey:
imageSave:
  path:
  default:
graphicsMagick:
  path:
webClient:
  domain:
  checkWord:
thread:
  num: 4
owner:
  email:
backup:
  path: